services:
  device-control-dashboard:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8117:80"
    networks:
      - app-network

    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  app-network:
    mode: bridge
