services:
  device-control-dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Передаем переменные окружения для сборки
        # Можно переопределить через .env файл или переменные окружения хоста
        VITE_HTTP_API_URL: ${VITE_HTTP_API_URL:-http://localhost:8081}
        VITE_WS_API_URL: ${VITE_WS_API_URL:-}
    restart: unless-stopped
    ports:
      - "8117:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
